### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by toyolife881** [toyolife881/protospace-37936#1]
#URL
https://protospace-37936.herokuapp.com/

**Comment by motomuun** [comment]
@toyolife881 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー詳細機能**

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
 所属と役職の内容が表示されていません。
<img width="1440" alt="スクリーンショット 2022-07-04 14 37 44 1" src="https://user-images.githubusercontent.com/65059944/177088448-bbef7bec-b00a-47b6-a8e3-fb4680107363.png">



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by toyolife881** [comment]
ご確認いただきありがとうございます!!

修正を行い、再度フォームを提出させていただきました。
引き続きご確認の程お願いいたします。

**Comment by motomuun** [comment]
@toyolife881 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by toyolife881** [comment]
ご確認ありがとうございました!!
